name: fast-jsonapi-serializer CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  check-format:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.0.0
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: crystal tool format --check

  specs:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.0.0
    steps:
    - uses: actions/checkout@v2

    - name: Install shards
      run: shards check || shards install

    - name: Run tests
      run: crystal spec
