name: Deploy docs

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.0.0
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install shards
        run: shards check --production || shards install --production

      - name: "Generate docs"
        run: crystal docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
